name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build
        run: tools/build
        env:
          VERBOSE: 1

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
